# Generated by Django 5.2.12 on 2026-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(verbose_name='N (nitrogen)')),
                ('p', models.FloatField(verbose_name='P (phosphorus)')),
                ('k', models.FloatField(verbose_name='K (potassium)')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField(verbose_name='pH')),
                ('rainfall', models.FloatField()),
                ('label', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soil_type', models.CharField(choices=[('Black', 'Black'), ('Clayey', 'Clayey'), ('Loamy', 'Loamy'), ('Red', 'Red'), ('Sandy', 'Sandy')], max_length=32)),
                ('crop_type', models.CharField(choices=[('Barley', 'Barley'), ('Cotton', 'Cotton'), ('Ground Nuts', 'Ground Nuts'), ('Maize', 'Maize'), ('Millets', 'Millets'), ('Oil seeds', 'Oil seeds'), ('Paddy', 'Paddy'), ('Pulses', 'Pulses'), ('Sugarcane', 'Sugarcane'), ('Tobacco', 'Tobacco'), ('Wheat', 'Wheat')], max_length=32)),
                ('nitrogen', models.FloatField()),
                ('potassium', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('fertilizer_name', models.CharField(choices=[('10-26-26', '10-26-26'), ('14-35-14', '14-35-14'), ('17-17-17', '17-17-17'), ('20-20', '20-20'), ('28-28', '28-28'), ('DAP', 'DAP'), ('Urea', 'Urea')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
